### ISSUE TITLE
зачем нужен данный реп?

### ISSUE THREAD

**Issue by makpif** [Linux4Yourself/Linux4Yourself.Book.Scripts#4]
я считаю что лучше встроить все скрипты в книгу (тем более что там должны быть команды по их созданию) в книгу, а данный реп заархивировать

**Comment by avmaisak** [comment]
предлагаю оставить его как вспомогательный. Тем более, я вчера говорил что можно встраивать в страницы некоторый скрипты и держать их с книгой не очень целесообразно.

**Comment by makpif** [comment]
ладно, пуст пока валяеться, если не будет в 1.0 использоваться - в архив
